import React from "react";

export default function Head()
{
    return(
        <React.Fragment>
            <title>About Us - Midnight Runners</title>
            <meta content="width=device-width, initial-scale=1" name="viewport" />
            <meta name="description" content="Generated by Baalais" />
            <link rel="icon" href="/favicon.ico" />
        </React.Fragment>
    );
}