import React from "react";

export default function Head() {
  return (
    <React.Fragment>
      {/* Iestatīt lapas virsrakstu */}
      <title>Midnight Runners</title>
      {/* Iestatīt meta tagus, lai nodrošinātu pareizu responsivitāti */}
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      {/* Iestatīt lapas aprakstu */}
      <meta name="description" content="Generated by Baalais" />
      {/* Pievienot favicon ikonu */}
      <link rel="icon" href="/favicon.ico" />
    </React.Fragment>
  );
}
