import Head from "next/head";
import Link from "next/link";
import React from "react";
import styles from "../styles/MainPage.module.css";
import mr from "../img/Midnight Runners.png";

export default function Home() {
  return (
    <>
      <Head>
        <title>Midnight Runners</title>
        <meta name="description" content="Generated by Baalais" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
      <header className={styles.header}>
        <div className={styles.logo}><img src={mr} alt="" /></div>
        <nav className={styles.nav}>
          <button className={styles.navButton}>Home</button>
          <button className={styles.navButton}>About</button>
          <button className={styles.navButton}>Services</button>
          <button className={styles.navButton}>Contact</button>
        </nav>
      </header>
      <main className={styles.main}>
        <img className={styles.mainPhoto} src="https://via.placeholder.com/600x400" alt="Placeholder" />
        <p className={styles.description}>
          This is a description area where you can provide details about the content or purpose of the page. It should give a brief overview to visitors.
        </p>
      </main>
    </div>
    </>
  );
}
